#!/usr/bin/env bash
#prints Hi in the 9th iteration. otherwise, prints best school
i=1
while [ $i -le 10 ]
do
    echo "Best school"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
